name: template_workspace

environment:
  sdk: ^3.12.2

workspace:
  - apps/app
  - packages/application
  - packages/foundation
  - packages/dependency_override
  - packages/designsystem
  - packages/domain
  - packages/infrastructure/firebase
  - packages/infrastructure/mock
  - packages/infrastructure/shared_preferences

dev_dependencies:
  # altive_lints: ^2.0.0
  flutter_lints: any
  melos: ^8.2.2

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.12.2
        flutter: ^3.44.6
      dependencies:
        collection: any
        flutter_hooks: any
        freezed_annotation: any
        go_router: ^17.0.1
        hooks_riverpod: ^3.3.1
        intl: any
        json_annotation: ^4.11.0
        logger: any
        riverpod: ^3.2.1
        slang: ^4.18.0
        slang_flutter: ^4.18.0
      dev_dependencies:
        alchemist: ^0.10.0
        build_runner: ^2.15.1
        flutter_gen_runner: any
        freezed: any
        go_router_builder: ^4.1.3
        json_serializable: ^6.13.0
        slang_build_runner: ^4.18.0
        test: any
    clean:
      hooks:
        post: melos exec --flutter --concurrency=3 -- "flutter clean" melos exec
          --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm
          Podfile.lock" melos exec --flutter --file-exists="macos/Podfile.lock"
          -- "cd macos && rm Podfile.lock"

  scripts:
    # ビルド関連
    build:app:
      description: 各プラットフォーム毎にモバイルアプリをビルドする
      steps:
        - build:app:android
        - build:app:ios
    build:app:ios:
      description: iOS向けにモバイルアプリをビルドする
      run: melos exec --scope="flutter_app" -- flutter build ipa
        --export-options-plist=ExportOptions.plist
        --dart-define-from-file=flavor/prd.json
    build:app:android:
      description: Android向けにモバイルアプリをビルドする
      run: melos exec --scope="flutter_app" -- flutter build appbundle
        --dart-define-from-file=flavor/prd.json

    # コード生成関連
    gen:
      description: build_runner, slangの生成コマンドを実行する
      steps:
        - gen:build
        - gen:slang

    gen:build:
      description: build_runner を使用してコードを生成する
      exec:
        command: dart run build_runner build -d
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
    gen:build:watch:
      description: build_runner watch を使用して、変更箇所を検知しつつコードを生成する。
      exec:
        command: dart run build_runner watch -d
        orderDependents: true
      packageFilters:
        dependsOn: build_runner

    gen:slang:
      description: slang を使用してコードを生成する
      exec:
        command: dart run slang
        orderDependents: true
      packageFilters:
        dependsOn: slang
    gen:slang:watch:
      description: slang watch を使用して、変更箇所を検知しつつコードを生成する。
      exec:
        command: dart run slang watch
        orderDependents: true
      packageFilters:
        dependsOn: slang

    gen:diff:main:
      description: main ブランチと差分のあるパッケージのみ build_runner と i18n の生成コマンドを実行します。
      steps:
        - gen:build:diff:main
        - gen:i18n:diff:main
    gen:build:diff:main:
      description: main ブランチと差分のあるパッケージのみ build_runner を使用してコードを生成します。
      exec:
        command: dart run build_runner build -d
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
        diff: origin/main...HEAD
    gen:slang:diff:main:
      description: main ブランチと差分のあるパッケージのみ slang を使用して国際化ファイルを生成します。
      exec:
        command: dart run slang
        orderDependents: true
      packageFilters:
        dependsOn: slang
        diff: origin/main...HEAD

    # dart fix関連
    fix:
      exec: dart fix --apply lib
      description: Run dart fix.
      packageFilters:
        dirExists: lib
    fix:check:
      exec: dart fix --dry-run lib
      description: Check dart fix.
      packageFilters:
        dirExists: lib
    fix:custom:
      description: すべてのパッケージに custom_lint の fix を実行します。
      exec: dart run custom_lint --fix
      packageFilters:
        dirExists: lib
        dependsOn: custom_lint

    # テスト関連
    test:golden:
      exec:
        command: flutter test --tags=golden
        orderDependents: true
      packageFilters:
        dependsOn: alchemist
        dirExists:
          - test
    test:golden:update:
      exec:
        command: flutter test --update-goldens
        orderDependents: true
      packageFilters:
        dependsOn: alchemist
        dirExists:
          - test
    test:ci:
      exec:
        command: flutter test --dart-define=CI=true
        failFast: true
      packageFilters:
        dirExists:
          - test

    test:e2e:
      description: AndroidエミュレータでPatrol E2Eテストを実行する
      run: patrol test --target integration_test/app_flow_test.dart --dart-define-from-file=flavor/dev.json
      packageFilters:
        scope: flutter_app

  ide:
    intellij:
      # Disabling IntelliJ's automatic configuration.
      # This is to support different build configurations for environments.
      enabled: false
