name: infrastructure_shared_preferences
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.12.2
  flutter: ^3.44.6

dependencies:
  collection: any
  domain:
    path: ../../domain
  flutter:
    sdk: flutter
  riverpod: ^3.3.2
  shared_preferences: null

dev_dependencies:
  flutter_test:
    sdk: flutter


  test: any

resolution: workspace
