name: packages_application
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.12.2

dependencies:
  domain:
    path: ../domain
  packages_foundation:
    path: ../foundation
  riverpod: ^3.2.1
  version: null

dev_dependencies:
  test: any

resolution: workspace
