name: packages_foundation
description: "This package provides core features of app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.12.2

dependencies:
  logger: any
  uuid: ^4.6.0

resolution: workspace
