name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

runs:
  using: "composite"
  steps:
  
    - name: ⚙️Setup mise
      uses: jdx/mise-action@v3
      with:
        cache: true

    # NOTE: 後述の melosコマンドが実行できないためPATHを通します。
    # PUB_CACHE: $HOME/.pub-cache に設定
    - name: ⚙️Export PUB_CACHE
      run: |
        echo "PUB_CACHE=$HOME/.pub-cache" >> "$GITHUB_ENV"
        echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: 🏃‍➡️Setup melos
      run: |
        MELOS_VERSION=$(cat pubspec.lock | yq ".packages.melos.version" -r)
        dart pub global activate melos $MELOS_VERSION
        dart run melos bootstrap
      shell: bash

    - name: 🔥Setup FlutterFire
      run: |
        dart pub global activate flutterfire_cli
      shell: bash
    
    - name: ♻️Regenerate Code
      run: melos run gen
      shell: bash
