name: Flutter Test
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flutter_test:
    name: 🧪Test
    runs-on: ubuntu-latest
    # runs-on: windows-latest
    timeout-minutes: 30
    steps:
      # チェックアウト
      - name: 💾Checkout
        uses: actions/checkout@v4

      # セットアップ
      - name: ⚙️Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # 実行
      - name: 🧪Test
        run: melos run test:ci
