name: TMP Update Goldens

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_goldens:
    name: Update Goldens
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 💾Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: ⚙️Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: 🖼️Update goldens
        run: melos run test:golden:update

      - name: ⬆️Upload updated goldens
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: updated-goldens
          path: packages/designsystem/test/components/goldens/ci/
